# Generated by Django 5.0.3 on 2024-03-27 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ferramenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('numSerie', models.IntegerField()),
                ('descricao', models.TextField()),
                ('imgFerramenta', models.ImageField(upload_to='ferramentas/')),
                ('dataAquisicao', models.DateField()),
                ('dataManutencaoFerramenta', models.DateField()),
                ('dataBaixa', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
    ]
