<<<<<<< HEAD
# Generated by Django 5.0.4 on 2024-04-30 15:11

=======
# Generated by Django 5.0.4 on 2024-05-13 23:09

import app_backend.models
import datetime
>>>>>>> origin/Alex
import django.db.models.deletion
import django_cpf_cnpj.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('codigoCargo', models.AutoField(primary_key=True, serialize=False)),
                ('nomeCargo', models.CharField(max_length=255)),
                ('descricaoCargo', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='Emprestimo',
            fields=[
                ('codigoEmprestimo', models.AutoField(primary_key=True, serialize=False)),
                ('matriculaFuncionario', models.CharField(max_length=20)),
                ('dataEmprestimo', models.DateField()),
            ],
            options={
            'unique_together': {('codigoEmprestimo', 'matriculaFuncionario')}, # Adiciona uma constraint de unicidade
            },
            
        ),
        migrations.CreateModel(
=======
>>>>>>> origin/Alex
            name='Ferramenta',
            fields=[
                ('idFerramenta', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
<<<<<<< HEAD
                ('numSerie', models.CharField(max_length=30)),
                ('descricao', models.TextField()),
=======
                ('numSerie', models.CharField(max_length=20, unique=True)),
                ('descricao', models.TextField(null=True)),
>>>>>>> origin/Alex
                ('imgFerramenta', models.ImageField(upload_to='ferramentas/')),
                ('dataAquisicao', models.DateField()),
                ('dataBaixa', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=30)),
            ],
<<<<<<< HEAD
            options={
            'unique_together': {('id', 'numSerie')}, # Adiciona uma constraint de unicidade
            }, 
=======
>>>>>>> origin/Alex
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('codigoSetor', models.AutoField(primary_key=True, serialize=False)),
                ('nomeSetor', models.CharField(max_length=255)),
                ('descricaoSetor', models.CharField(blank=True, max_length=255, null=True)),
<<<<<<< HEAD
=======
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('codigoEmprestimo', models.AutoField(primary_key=True, serialize=False)),
                ('matriculaFuncionario', models.CharField(max_length=20)),
                ('dataEmprestimo', models.DateField(default=datetime.date.today)),
                ('dataDevolucao', models.DateField(null=True)),
                ('observacoes', models.TextField(null=True)),
                ('idFerramenta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_backend.ferramenta')),
            ],
        ),
        migrations.CreateModel(
            name='ManutencaoFerramenta',
            fields=[
                ('codigoManutencao', models.AutoField(primary_key=True, serialize=False)),
                ('tipoManutencao', models.CharField(max_length=15)),
                ('dataInicio', models.DateField(default=datetime.date.today)),
                ('dataFinal', models.DateField(null=True)),
                ('idFerramenta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_backend.ferramenta')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('idFuncionario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('matriculaFuncionario', models.CharField(max_length=20, unique=True)),
                ('cpf', django_cpf_cnpj.fields.CPFField(max_length=14, unique=True)),
                ('imgFunc', models.ImageField(blank=True, null=True, upload_to=app_backend.models.upload_path)),
                ('codigoCargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_backend.cargo')),
                ('codigoSetor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_backend.setor')),
>>>>>>> origin/Alex
            ],
        ),
        migrations.CreateModel(
            name='itemEmprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataDevolucao', models.DateField(blank=True,null=True)),
                ('observacoes', models.TextField()),
                ('codigoEmprestimo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_backend.emprestimo')),
                ('numSerie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_backend.ferramenta')),
            ],
            options={
            'unique_together': {('id', 'numSerie')}, # Adiciona uma constraint de unicidade
            },
        ),
        migrations.CreateModel(
            name='ManutencaoFerramenta',
            fields=[
                ('codigoManutencao', models.AutoField(primary_key=True, serialize=False)),
                ('tipoManutencao', models.CharField(max_length=15)),
                ('dataInicio', models.DateField()),
                ('dataFinal', models.DateField()),
                ('numSerie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_backend.ferramenta')),
            ],
            options={
            'unique_together': {('codigoManutencao', 'numSerie')}, # Adiciona uma constraint de unicidade
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('matriculaFuncionario', models.CharField(max_length=15)),
                ('cpf', django_cpf_cnpj.fields.CPFField(max_length=14)),
                ('imgFunc', models.ImageField(upload_to='funcionarios/')),
                ('codigoCargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_backend.cargo')),
                ('codigoSetor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_backend.setor')),
            ],
            options={
            'unique_together': {('id', 'matriculaFuncionario')}, # Adiciona uma constraint de unicidade
            }, 
        ),
    ]
