# Generated by Django 5.0.4 on 2024-05-20 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ferramenta',
            old_name='idFerramenta',
            new_name='codFerramenta',
        ),
        migrations.RenameField(
            model_name='manutencaoferramenta',
            old_name='idFerramenta',
            new_name='codFerramenta',
        ),
    ]
