# Generated by Django 5.0.3 on 2024-04-01 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('codigoSetor', models.IntegerField(primary_key=True, serialize=False)),
                ('nomeSetor', models.CharField(max_length=255)),
                ('descricaoSetor', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
