# Generated by Django 5.0.4 on 2024-05-13 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimo',
            old_name='idFerramenta',
            new_name='numSerie',
        ),
    ]
