# Generated by Django 5.0.4 on 2024-05-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0002_rename_idferramenta_ferramenta_codferramenta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='matriculaFuncionario',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
