# Generated by Django 5.0.6 on 2024-06-10 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0002_remove_ferramenta_databaixa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='numSerie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_backend.ferramenta'),
        ),
        migrations.AlterField(
            model_name='manutencaoferramenta',
            name='codFerramenta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_backend.ferramenta'),
        ),
    ]
