# Generated by Django 5.0.4 on 2024-05-20 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0003_alter_funcionario_matriculafuncionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='matriculaFuncionario',
            field=models.CharField(max_length=50),
        ),
    ]
