# Generated by Django 5.0.3 on 2024-04-17 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0003_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('codigoEmprestimo', models.AutoField(primary_key=True, serialize=False)),
                ('matriculaFuncionario', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='ferramenta',
            name='dataManutencaoFerramenta',
        ),
        migrations.AlterField(
            model_name='ferramenta',
            name='status',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('matriculaFuncionario', models.CharField(max_length=15)),
                ('imgFunc', models.ImageField(upload_to='funcionarios/')),
                ('codigoCargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_backend.cargo')),
                ('codigoSetor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_backend.setor')),
            ],
        ),
        migrations.CreateModel(
            name='itemEmprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoEmprestimo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_backend.emprestimo')),
                ('numSerie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_backend.ferramenta')),
            ],
        ),
        migrations.CreateModel(
            name='ManutencaoFerramenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoManutencao', models.CharField(max_length=15)),
                ('numSerie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_backend.ferramenta')),
            ],
        ),
    ]
