# Generated by Django 5.0.3 on 2024-04-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0004_emprestimo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setor',
            name='codigoSetor',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
