# Generated by Django 5.0.4 on 2024-04-17 23:41

import django_cpf_cnpj.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0005_alter_setor_codigosetor'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='cpf',
            field=django_cpf_cnpj.fields.CPFField(max_length=14, null=True),
        ),
    ]
