# Generated by Django 5.0.4 on 2024-04-23 23:17

import django_cpf_cnpj.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0006_funcionario_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=django_cpf_cnpj.fields.CPFField(max_length=14),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='imgFunc',
            field=models.ImageField(blank=True, null=True, upload_to='funcionarios/'),
        ),
    ]
