# Generated by Django 5.0.6 on 2024-06-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0007_alter_emprestimo_matriculafuncionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='matriculaFuncionario',
            field=models.CharField(max_length=50),
        ),
    ]
