# Generated by Django 5.0.4 on 2024-04-30 00:44

import django_cpf_cnpj.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0008_alter_funcionario_imgfunc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ferramenta',
            name='numSerie',
            field=models.IntegerField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=django_cpf_cnpj.fields.CPFField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='matriculaFuncionario',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
