# Generated by Django 5.0.4 on 2024-05-02 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0009_alter_ferramenta_numserie_alter_funcionario_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itememprestimo',
            name='dataDevolucao',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='itememprestimo',
            name='observacoes',
            field=models.TextField(null=True),
        ),
    ]
