# Generated by Django 5.0.6 on 2024-06-26 02:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0009_alter_emprestimo_matriculafuncionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='matriculaFuncionario',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Somente números são permitidos.')]),
        ),
    ]
