# Generated by Django 5.0.4 on 2024-05-02 01:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0010_itememprestimo_datadevolucao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='dataEmprestimo',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
