# Generated by Django 5.0.4 on 2024-05-02 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0011_emprestimo_dataemprestimo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ferramenta',
            name='id',
        ),
        migrations.AlterField(
            model_name='ferramenta',
            name='numSerie',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='itememprestimo',
            name='codigoEmprestimo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens', to='app_backend.emprestimo'),
        ),
        migrations.AlterField(
            model_name='itememprestimo',
            name='numSerie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprestimos', to='app_backend.ferramenta'),
        ),
    ]
